### ISSUE TITLE
DiffEqBase broken on Julia v1.0

### ISSUE THREAD

**Issue by dkarrasch** [SciML/DiffEqBase.jl#465] opened 2020-03-20 09:21 UTC
I can't seem to get DiffEqBase running on Julia v1.0.5 with the last DiffEqBase version `DiffEqBase v6.23.0` (starting from v6.24 we seem to require Julia v1.3 anyway):
```julia
julia> using DiffEqBase
[ Info: Precompiling DiffEqBase [2b5f629d-d688-5b77-993f-72d75c75574e]
ERROR: LoadError: LoadError: UndefVarError: eachcol not defined
```
The reason seems to be that

https://github.com/JuliaDiffEq/DiffEqBase.jl/blob/36fcd87853449fa2f3daa6249d1f52b89f4af424/src/operators/basic_operators.jl#L103-L104

extend `Base.eachcol` and `Base.eachrow`. However, on Julia v1.0 these are not exported by `Base`, but by `Compat`. Would it be possible to fix that and get a working `v6.23.1`? Perhaps, one could do that by something along the lines
```julia
if VERSION < v"1.1.0-DEV.792"
  import Compat: eachcol, eachrow
else
  import Base: eachcol, eachrow
end
```
and then omit the qualifier in the above quoted lines? Well, or put the above lines in such a VERSION branching. I understand that this is ugly, but it wouldn't leak into newer versions anyway.

**Comment by mateuszbaran** [comment] 2020-03-20 09:22
It's essentially duplicate of https://github.com/JuliaDiffEq/DiffEqBase.jl/issues/462 which was fixed and then broken again by https://github.com/JuliaRegistries/General/pull/11221

**Comment by dkarrasch** [comment] 2020-03-20 09:45
So how was it fixed?

**Comment by mateuszbaran** [comment] 2020-03-20 10:02
By setting stricter bounds: https://github.com/JuliaRegistries/General/pull/11148

**Comment by dkarrasch** [comment] 2020-03-20 10:25
Oh, now I see, and the other registry PR relaxed the stricter bounds back again?

**Comment by mateuszbaran** [comment] 2020-03-20 10:28
Yes, exactly.

**Comment by ChrisRackauckas** [comment] 2020-03-20 13:52
So the bounds were updated to avoid this issue since I couldn't quickly figure out why Compat wasn't working. If you wanted to take a stab at setting this up for one last v1.0 release, be my guest. I don't want to put too much effort into v1.0 though since it really needs to be deprecated soon: there's a lot of v1.0 compiler bugs that stop most of the "deep" features from working (Cassette.jl, ModelingToolkit.jl, SparsityDetection.jl, etc.) so it will never be the best experience. However I want to keep the basics working, and am not sure if it's better to chase Compat for that or just to bound it and leave it stable.

**Comment by mateuszbaran** [comment] 2020-03-20 13:58
I think marking 6.22 and 6.23 as not 1.0-compatible (what has already been done) is a fair solution. Unfortunately I don't know how to prevent future releases of `DiffEqBase` from incorrectly updating compatibility.

**Comment by ChrisRackauckas** [comment] 2020-03-20 23:33
We need to figure out how to make JuliaRegistrator work on a branch for this, since we don't want to tag from master here.

**Comment by KristofferC** [comment] 2020-03-23 10:47
https://github.com/JuliaRegistries/General/pull/11148 is not a correct way to change bounds. The registry is using a compressed format and just going in and changing an entry is unlikely to give a good result.

**Comment by GunnarFarneback** [comment] 2020-03-23 10:48
Yes, the patch was incorrect and didn't actually do anything.

**Comment by ChrisRackauckas** [comment] 2020-03-25 17:50
Re-fixed by https://github.com/JuliaRegistries/General/pull/11397

**Closed by ChrisRackauckas** 2020-03-25 17:50 UTC
